### ISSUE TITLE
Suggestion on how to deploy and warning

### ISSUE THREAD

**Issue by rami-maalouf** [georgiaberg/hackhackhack#5]
- [NextJS frontend + flask backend](https://vercel.com/templates/python/nextjs-flask-starter)
- [NextJS frontend + FastAPI backend](https://github.com/digitros/nextjs-fastapi)
- [NextJS frontend and backend + FastAPI backend (so 2 backends in 1 server)](https://github.com/psycho-baller/nextjs-and-fastapi-backend)

I was also a hacker and was just going through some of the htn projects out there and found yours. I like yr idea. My project also was related to journaling. You can find [the repo here](https://github.com/psycho-baller/journal-genius). I had a different idea on how AI can help you

P.S: you might wanna hide the Cohere API keys and DB URL. And also make new ones(API key and DB password or smthn) since the ones that are out rn will forever be on the internet and you don't want that

**Comment by momalekabid** [comment]
thanks for the heads up about the raw api keys and db auth. not sure if we'll end up deploying as we're all pretty busy with school/work but if we do we'll be sure to look into your advice.
